
name: Build LaTeX Document

on:
  push:
    branches:
      - master
      - latex
  pull_request:
    branches:
      - master
      - latex

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload PDF file
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
